templates:
  utter_ask_cuisine:
    - text: "what cuisine do you like?"
  utter_ask_brand:
    - text: "what hotel brand do you like to book in?"
  utter_ask_num_people:
    - text: "how many people?"
  utter_ask_outdoor_seating:
    - text: "do you want to seat outside?"
  utter_ask_preferences:
    - text: "please provide additional preferences"
  utter_ask_feedback:
    - text: "please give your feedback"
  utter_submit:
    - text: "done!"
  utter_slots_values:
    - text: "got slots:\n
             - cuisine: {cuisine}\n
             - num_people: {num_people}\n
             - outdoor_seating: {outdoor_seating}\n
             - preferences: {preferences}\n
             - feedback: {feedback}"
  utter_noworries:
    - text: "you are welcome :)"
  utter_chitchat:
    - text: "chitchat"
  utter_ask_continue:
    - text: "do you want to continue?"
  utter_wrong_cuisine:
    - text: "cuisine type is not in the database, please try again"
  utter_wrong_brand:
    - text: "brand type is not in the database, please try again"
  utter_wrong_num_people:
    - text: "number of people should be a positive integer, please try again"
  utter_wrong_outdoor_seating:
    - text: "could not convert input to boolean value, please try again"
  utter_restart:
    - text: "restarting"

